spring.application.name=BootCamp_Santander_AI
spring.datasource.url=jdbc:h2:mem:petshop
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=system-pet-db
spring.datasource.username=iadnfpuix3m43x73nx743x84xyn49ynx9cucr0nxr328cxm2398cm3280432nmxx4025nx328mx

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
